services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/query.log:/var/log/prometheus/query.log

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"
      - "--query.log-file=/var/log/prometheus/query.log"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  ai-app:
    build:
      context: ./anomaly-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]


  prom-optimizer:
    build: ./prom-optimizer
    container_name: prom-optimizer
    ports:
      - "8090:8090"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - QUERY_LOG_FILE=/querylog/query.log
    volumes:
      - ./prometheus/query.log:/querylog/query.log
    depends_on:
      - prometheus